services:
  my_server:
    build:
      context: ./../
      dockerfile: ./MyBoardGameServer/Dockerfile
    image: myserver:latest
    container_name: myserver
    ports:
      - '8080:8080' # HTTP
      - '8081:8081' # SSL
    depends_on:
      - postgres
    restart: on-failure
    networks:
      - default
    environment:
      - ASPNETCORE_ENVIRONMENT=Production

  postgres:
    image: postgres:15
    hostname: postgres
    container_name: mypostgres
    ports:
      - 5432:5432
    volumes:
      - ./volumes/postgres/:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    restart: unless-stopped
    networks:
      - default

